FROM docker.io/library/golang:1.23-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/app .

FROM docker.io/library/alpine:3.20
COPY --from=build /out/app /app
EXPOSE 8080
ENTRYPOINT ["/app"]
